services:
    hs11.codegenerator.controller:
        class: hs11\codegenerator\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@request'
            - '@template'
            - '@user'

    hs11.codegenerator.listener:
        class: hs11\codegenerator\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '@?files.factory'
        tags:
            - { name: event.listener }
